loathers/garbage-collector

src/fights.ts
src/index.ts
src/outfit.ts

Added some checks on various part of the codes, that you actually have the item/skill that it is trying to use. 
(Basically what i needed in order to be able to run the script successfully from start to end, minus the parts where i solved the problem by just putting some lines into comments or where my solution wasn't general enough)
Also added some support for mumming trunk. Use the meat drop costume on your meat drop familiar. I figured this change was neutral enough that i could include it.

various checks

---

KoLmafia/scripts/garbage-collector/garbo.js
src/index.ts

Presently due to a typo we never use numberology. Now we do.

Use Numberology

---

KoLmafia/scripts/garbage-collector/garbo.js
dependencies.txt
src/index.ts
src/mood.ts

As suggested- for the scripts that we depend on that have svn repositories (these being Ezandora's Bastille, Gain, and Briefcase scripts), have these in dependencies.txt so they get automatically installed when needed. As no such repository exists for pantogram.ash, but we are only using it for two visitUrl calls, these visitUrl calls have been hardcoded in, removing the requirement. Finally, fixed case error in Briefcase invocations.
Resolves #11

Remove pantogram.ash dependency, make other dependencies explicit

---

KoLmafia/scripts/garbage-collector/garbo.js
src/fights.ts

Prevents abort on encountering DMT noncombat by skipping it- this might not be wholly desirable behaviour, some users may wish to set an item to duplicate?
Resolves #8

Don't abort on DMT noncombat

---

KoLmafia/scripts/garbage-collector/garbo.js
src/familiar.ts
src/index.ts
src/outfit.ts

Presently, a maximizer bug means that maximizing for sea may report fail as part of our main outfit maximizer even when it is able to get us and our familiar waterbreathing. This PR makes a number of changes to smooth this out.
- If we are making an underwater outfit, we maximize `sea -tie` as a final step to ensure we can breathe. This may disrupt retrocape crit strategies, but as that is our lowest priority crit strategy, if it does disrupt it they weren't going to get the pointer finger meat either way, so we're okay with it. 
- Robortenders will be fed a Bloody Nora in addition to all other drinks (this is presently suboptimal for people who do not have digitize, but hopefully we will drag copies into the sea for people without a source terminal shortly)
- Urchin Urchin has been added …

Sea maximization

---

.github/workflows/build.yml
.prettierignore
.vscode/settings.json
README.md
babel.config.js
package.json
src/fights.ts
src/outfit.ts
webpack.config.js
yarn.lock

This PR adds a GitHub workflow named Build & Lint. It runs whenever someone submits a PR to `main` or directly pushes to it. This allows maintainers and contributors to quickly check if the submitted code is OK, directly from the web UI.
This PR also includes changes needed to enable the workflow:
- ESLint and Prettier are added to the project's `devDependencies`
- Added a `yarn run lint` script
- Added a `.prettierignore` file

ci: Add 'Build & Lint' workflow 

---

.github/workflows/build.yml
.vscode/settings.json
src/index.ts

Will bander-run to get the ingredients from black forest and spooky forest. No other methods of freeruns supported (except, of course, boots). Will tune latte to optimality. Wont' seek out carrots, but will use them.

latte support added

---

src/index.ts

As of now, script will enter an infinite loop if you have a ghost quest in a presently-locked zone. The only places where that can happen are the madness bakery, the overgrown lot, and the skeleton store.

start market square quests to open ghost zones

---

src/fights.ts

Presently, we abort if we encounter a time-spinner prank during our pygmy fights. This PR adds more resilience by expressly meatkilling any time-spun pranksters we encounter during pygmy times.

Improve resilience against time-spinner pranks

---

src/diet.ts

If the user ever chooses to proceed with zero moon pills, save that so they don't have to catch the user confirm in future.

Save user's desire to skip moon pill checking

---

src/index.ts

This should prevent problems with new features (cf lastCopyableMonster vs feelNostalgiaMonster)

Add since to main

---

package.json
src/fights.ts
src/index.ts
src/mood.ts
src/outfit.ts
yarn.lock

Major upshot of this change is we should now be better at handling envyfish eggs without digitize and starting embezzler chains without VIP key or with the day's photocopy already used, as well as genericizing the interface to make adding more copies later easier.
Hopefully.

Overhaul embezzler logic

---

src/fights.ts

Previously on gossip girl, it would check with have() for eldritch essence, which uses availableAmount(), which checks closet and hagnks. We care only about items in inventory, and thus must use itemAmount().

fix small eldritch tentacle fight bug

---

src/diet.ts
src/index.ts

Adds the ascending global option (defaulting to false) that determines if we should attempt to use borrowed time. Also, adds etched hourglass use.

Only use borrowed time if ascending

---

src/lib.ts

I was getting an error message about not having a pair of stomping boots (this is true).  After looking at the code, I suspect that the free run logic is missing a parenthesis for the bandersnatch + ode check.  I didn't get to test this fix since I had run out of adv by the time I got around to looking at the error.

Added missing parenthesis check for bander ode check/call.

---

src/index.ts
src/lib.ts
src/outfit.ts

Currently approximates value of familiar weight using a linearization based on your meat familiar's leprechaun multiplier.
May overvalue bjorn/crown in the maximizer (it gives a bonus on top of its regular score), but bjorn is pretty much always worth wielding anyways.
Bjorn-familiar list is not exhaustive, but covers most bases.

Pick bjorn familiars based on drops and enchantment, rather than just enchantment

---

src/lib.ts

You'll get those drops eventually, and so it is better to use familiars that give +meat% on embezzlers and get those items from free fights or regular barf monsters

ignore familiars that drop items when picking your embezzler bjorn choice

---

src/stash.ts

- Stop pulling foldables once we've found the item we want
- Only attempt to pull items that are actually in the stash
- Differentiate between items not being in the stashclan's stash and something failing with the pull

Assorted stash behaviour changes

---

src/combat.ts
src/dailies.ts
src/diet.ts
src/fights.ts
src/index.ts
src/outfit.ts

Calculate value of pantsgiving assuming horseradish with seasoning and sans-mayozapine; verify we have enough turns to get an extra fullness, and add as a bonus equip.
Add a horseradish() function after just about every fight I can find. There must be a better way to do that, though.
Resolves #77

pantsgiving support

---

src/fights.ts

Fixed a bug where the seal fights would abort if you didn't have any Claw of the Infernal Seals in inventory, but one was available in Hangk's.

Fixed seal fight abort

---

src/diet.ts

There are two potentially controversial choices that this script makes:
1. It aborts if you have an incorrect mayo in your mouth. Mayodiol is the big threat here, but Mayonex can also be bad.
2. It exclusively uses the Mayo Minder. This is because I'm concerned about accidentally filling your mouth with a mayo and then not wanting to use that mayo.
Resolves  #219

add mayo support

---

src/index.ts

I often wind up only eating a few sausages (since I don't have Bind Lasagmbie perm'd/other MP intensive scripts running), so I added code to eat more sausages if we're at the end of the garbo run.  Tested this today and it ran successfully.

Eat remaining sausage

---

package.json
yarn.lock

We can start using libram's clan support later, but for now, we should upgrade to make Guzzlr.abandon() and Guzzlr.havePlatinumDrink() work properly

upgrade libram for guzzlr reasons

---

src/lib.ts

This is a temporary measure, until we come up with a system for deciding between digitized monsters and backups

Add skeleton store and overgrown lot to blacklist

---

src/lib.ts

Despite what it may seem, this _did_ change the behavior of pickBjorn() for me, and it changed it for the better.
PickBjornModes are numbers, so previously this was being parsed as
`mode === PickBjornMode.FREE ? 0 : (baseMeat + mode) === PickBjornMode.EMBEZZLER ? 750 : 0`, which always returns 0. Or somethign else weird was happening, but adding these parantheses changed the behavior.

add parantheses to the meatVal part of generateBjornList

---

src/dailies.ts

Cast extract jelly one more time after using macrometeorite or replace monster, before running away. Currently the last monster replace is wasted.

Don't wasted final monster replace when extracting jelly

---

src/lib.ts

If we're ascending, we can safely use peppermint parasols, then on ascension the counter is reset.
I'm keeping it ascension-only in case somebody wants to use parasols later or something.

Add peppermint parasols as freerun option

---

src/lib.ts
src/outfit.ts

This will prevent swapping enthroned\bjorned familiars over and over after a maximize cache is hit when garbo is manually setting the familiars for drops.
This needs an updated libram

Set preventSlot crown-of-thrones & buddy-bjorn when maximizing

---

src/dailies.ts
src/familiar.ts

Motivated by billybobsteve's issue in discord, and the following startling result:
```
> js numericModifier(Familiar.get("Leprechaun"), "Leprechaun", 1, Item.get("none"))
Returned: 0.0
```
Not touching bjorn code yet because this is a bit of an emergency patch situation

remove "Leprechaun" and "Fairy" modifiers from meatFamiliar()

---

src/combat.ts
src/dailies.ts
src/fights.ts
src/index.ts
src/lib.ts

- use simpler macro for all non-meat fights
- kill() Macro that nukes if regular attacks miss, hp falls below 25%, or past round 20
- ghost bustin, ensure enough stuns can be used to not get hit
- seal clubbin, use Furious Wallop and smacks
- use $skill & $item instead of strings where appropriate
- inject a macro that can deal with tentacles if you have eldritch attunement
- use Extract, Pocket Crumbs, & porquoise-handled sixgun in meatKill() by checking monster hp and passive damage from vykea + other passive damage sources (monster manuel only)
- use abstraction on machine tunnel monsters to get item if profitable
- tryHaveSkill doesn't need to accept a string, be explicit. Use for all skills that aren't dynamic
- add tryHaveItem to simplify macro more if reusable combat items are …

Combat improvements

---

src/fights.ts

This is particularly important if we're ascending afterward, but I think we should still check even if we're not.

Check for thesis again after profchains

---

src/fights.ts

Carrots are available for all ascension types, including Goo and CS--we don't want to waste free runs getting a carrot latte if we aren't going to ever use that latte, which should only happen if we have rawhide and cajun as ingredients.

only freerun for carrots if we have cajun and rawhide

---

src/fights.ts

There's no reason to execute the mood for a free run since there's no benefit from effects.

Remove free fight mood execute from FreeRunFight

---

mafia/data/garbo_settings.txt
src/fights.ts
src/index.ts
src/lib.ts

I find myself slamming on esc a lot to stop garbo when testing, so here is a way to abort it safely from the relay script instead.
Current points where the abort can happen:
- After a single free fight or kill
- After the entire embezzler meat chain is finished
- After the entire embezzler weight chain is finished
- After any other embezzler fight
- After a single barf fight

Add a setting to interrupt garbo

---

src/mood.ts

we currently get random effects from universal seasoning & glenn's golden dice, which is bad! 
Tied behind a user pref because we only need to call it once and it's a lot of effects.
Credit to aen for the list.

uneffect dangerous effects for stasis

---

.prettierignore
package.json
yarn.lock

- Add `yarn deploy <mafia root path>` to copy locally built garbo files & all other required files to a directory. Uses copyfiles package and is cross-platform (tested on linux and windows).
- Add `yarn lint:fix` which runs eslint and prettier and applies changes
- Build types before running `webpack --watch`
- Add more ignores to .prettierignore (matches .gitignore now)

yarn deploy

---

src/dailies.ts

Replaced hex key (not consumed) by instructions (consumed) in vykea cost estimation

Replace hex key (not consumed) by instructions (consumed) in Vykea cost estimation

---

src/fights.ts

This is a not-great fix that nevertheless should patch an issue that Scotch ran into earlier today. 
I would like to, in the near future, re-evaluate the relationship between wanderer.ts, fights.ts, and embezzler.ts, because I'm pretty sure there is a way to make this much, much shorter, and that may involve excising location from EmbezzlerOptions. But for now I would like to get this fix in so that it's fixed.

don't try to put backups in non-backup zones

---

src/outfit.ts

Right now, garbo doesn't actually pass any of our default preventEquips to the maximizer, because it passes a different array of preventEquips. This changes that.

prevent all our various equips within the outfit functions

---

src/outfit.ts

Mafia doesn't currently track the most recent buff, so we can't optimize based on that. But we can optimize not based on that!

add preliminary support for the daylight shavings helmet

---

src/familiar.ts

Right now, if an outfit function gets called before a particular function in our daily tasks, we will lock in a non-robortender familiar as our meat familiar. While ultimately easily avoidable, this behavior is bizarre and dumb and can be rectified by this.

hardcode the robortender into meatFamiliar()

---

src/embezzler.ts

Move "starter" sources to the back--they're more valuable than other copies, so we don't want to blow through them unless needed. Move profchain sources behind the pocket wish, because they're fake EmbezzlerFights. keep backup just behind wanderers.

resequence existing embezzler sources

---

src/fights.ts

kevinzana (#591276) had an issue where garbo banished a gregged embezzler while trying to initialize the digitize counter, despite having already started it. Adding some wiggle room to the counters (extending into -3), as well as a macro that won't banish the embezzler.

don't react as poorly to mistimed digitizes

---

src/fights.ts
src/index.ts
src/mood.ts
src/potions.ts

-allow for overriding of effects and duration
-move useAsValuable outside of the class to keep that behavior private to the module
-create static convenience versions of the useful functions
-add in "pocket wish" potions for valuable meat drop effects (this will never be worth it without PYEC)

Rework Potions

---

src/outfit.ts

- mafia thumb ring based on valueOfAdventure
- lucky gold ring based on what currencies could drop (currently over estimated if the volcoino hasn't dropped yet). Uses day passes, karma shawarma, & good dread consumables for values. Hobo nickel is set at 100, but garbo already closets these so w/e
- Update Mr. Cheeng's spectacles to 400 based on discussion in discord. We speculate the drop items are any pvpable potion that will never be banned by standard restrictions, which seems to check out. Could be dynamically generated later if we can get the list of standard items for the current year
- Don't add bonuses to maximizer string if the equipment is unavailable

Bonus drop items update

---

src/fights.ts

we Use the Force at the same time as olfacting, meaning that olfactedMonster doesn't update properly

hotfix olfaction issue

---

src/fights.ts
src/index.ts
src/lib.ts

- Burn mp again after using express card or license to chill
- Don't maximize mp unless pyec or license will be used
- Burn mp after restoring hp or mp, leaving a threshold of double the target restore, to use any extra mp after a large restore (like  from eating a sausage)
- Enable allowNonMoodBurning only if not ascending, as the extra turns would be wasted
- Enable summon burning if not set, but don't burn on libram summons as that is handled manually based on sale price

More mana burning

---

src/index.ts
src/outfit.ts

This code was added due to behavior with respect to default maximize options that has since been changed; it is now redundant.

cut now-redundant preventEquip logic

---

src/diet.ts
src/potions.ts

* limit potions to once per day
* only consider the cheapest of items with the same adventure yield
* properly count existing gregarious charge

Diet tweaks - limit potions, cheapest food, gregarious counts

---

src/lib.ts
src/mood.ts

Reserve the MP we're about to restore before each fight when casting our mood. That way we're not constantly using MP restores to get more turns of Pasta Eyeball.

Don't use MP restores every fight.

---

src/dropsgear.ts
src/fights.ts

Right now, if determineDraggable...() sends us to zones with free intro adventures, we will fail to fight a void monster, and then get a void monster in the middle of drunk pygmies.
Instead, we don't do that.

stop running into issues with void monsters during drunk pygmies

---

src/fights.ts

As-is, we appear to be sabering pygmies only when our crate strategy _is_ "Saber", rather than when it isn't.

do pygmy-saber logic right instead of wrong

---

src/diet.ts
src/index.ts

A user had a diet crash when their diet contained a food-cone but they had not yet opened barf; moved logic to open barf earlier.

open barf earlier

---

src/combat.ts
yarn.lock

Summary of changes:
- permit longer stasis if waiting for bittycar, hobo monkey or bjorn - I've seen them sometimes happen quite late in fights when I went to look at my pre-garbo logs
- use a dictionary over a seal tooth for stasis if possible
- throw OPS ahead of stasis to avoid double round awkwardness
- redo the stasis code to have a single macro, with variables controlling the round count and whether to care about the monster HP
- move the porquoise gun ahead of the stasis loop due to HP requirement awkwardness
Known issue in need of addressing:
- `.kill()` would require a mild adjustment to deal with the longer stasis

meat stasis rework

---

src/combat.ts

Right now, when macros are printed to the CLI (and thus the session log), the whitespace is omitted, rendering them very hard to read and parse. This PR uses semicolons to join rather than linebreaks, which will actually appear on the CLI.

Use-semicolons

---

src/embezzler.ts
src/fights.ts
src/index.ts

bit of an omnibus PR:
- Makes messaging for unprepared characters more dramatic
- Fixes issue with talking to the Old Man when underleveled
- Removes the use of `.some(have)` for items (because that always returns true; it's fine for familiars and skills)
- Fixes non-destructive but recurring issue where garbo attempts to do the romance arrow in the sea by switching to meat familiar after completing profchain

support for unsupported character states

---

src/outfit.ts

Reverts Loathing-Associates-Scripting-Society/garbage-collector#846
It turns out, this interacts poorly with the ongoing bjorn-maximizer bug.

Revert "add -tie to maximizer strings"

---

mafia/data/garbo_settings.json
src/clan.ts
src/diet.ts
src/embezzler.ts
src/index.ts
src/lib.ts

Idea is for the auto confirmation to handle user confirms in a way aiming to ensure garbo keeps running and chooses options anticipating the most meat possible. To me it's expected that the optimal decision might not be made and that's fine since someone had to explicitly set this pref.

add auto confirmation handling

---

src/embezzler.ts

As it stands, we can hit a gregarious monster during startWandererCounter, invalidating our current getNextEmbezzlerFight. This stops that by creating a temporary variable for our post-fight actions, and then only actually deciding the next embezzlerFight at the end.

set nextFight later

---

src/dailies.ts
src/fights.ts

This goes hand-in-hand with the recent-ish clarasBellClaimed tracking; we want to check this before doing volcano dailies, and we want it to re-enter nicely.

initialize NEP quest before volcano stuff

---

src/relay/components/BooleanInput.tsx
src/relay/css/App.scss

Realistically this should be fixed by registering the properties as actual booleans or converting them to booleans before it reaches this input.

Allow string boolean, fixes #895

---

src/combat.ts
src/familiar.ts
src/index.ts

Meatify Matter will try to trigger on the last possible free fight wanderer if the ascend flag is true, or any time under 50 adventures left if no free fight wanderers are available

Improve meatify logic when ascending

---

src/fights.ts

Changed sabering for maps in Grimace to not be tentaclable to try and prevent acquiring eldritch attunement on reentry

Saber Forces aren't tentaclable

---

src/fights.ts

This is to avoid the Barf NC which takes a turn

Use Uncle Gator's instead of Barf for jelly fishing

---

src/embezzler.ts

Handles edge cases where we have both copiers but one or both of them are locked out due to having a non-embezzler copied within

Updated putty and rain-doh copy estimates

---

src/yachtzee.ts

This is also more in line with the estimate garbo uses elsewhere in the codebase

Revise embezzler estimate from 3.5x VOA to 3.0x VOA

---

src/yachtzee.ts

We tend to have phat loot and ur-kel's active when we're buffing up with potions, which causes us to not use those potions

Shrug yachtzee-irrelevant songs

---

src/yachtzee.ts

This is only triggered after shrugIrrelevantSongs(), so the only songs that are left to shrug would be polka, chorale and ballad, and polka is the cheapest to buff up again (of the 3).
However, if we don't have the skill to buff up again (i.e. the effect was obtained from a buffbot prior to running garbo), then don't shrug polka (else we would run the rest of garbo without it).

Shrug polka if we are out of song slots for ode

---

src/fights.ts
src/index.ts
src/mood.ts
src/yachtzee.ts

It is egregiously bad for character levels < 35 (for barf tourists; it may be marginally profitable for embezzlies and yachtzees at a lower level), even with MMJs. We use MMJs as a benchmark to see if it is indeed profitable for the account to run it.

Only use pasta eyeball when profitable

---

src/fights.ts

This caused an abort for me today because it didn't acquire the cans then tried to throw them

Fix gas can acquire to match macro usage

---

mafia/dependencies.txt

KoL-MineVolcano and combo have switched to recommending they be installed using git. Switch the dependencies accordingly.

Prefer git dependencies for repos that prefer git installs

---

src/familiar/index.ts
src/familiar/itemFamiliar.ts
src/fights.ts

@SSBBHax I hope I successfully pinged you.
This does:
- Add the gnome as a possible pull for drum machines
- Assign the gnome a bonus value under the assumption it'll hit about 70 lbs
- Sort our fairies by drop-value rather than by leprechaun multiplier
This does not:
- Ever use the gnome when we have a remotely better fairy, even if we're wasting it
- Add the gnome as what the kids call a "constant value familiar"
- Actively inform you that the oldest human-planted tree with a known planting date resides in the island nation of Sri Lanka, whose chief exports include tea and rubber

be a little smarter about our selection of fairies

---

src/outfit.ts
src/yachtzee.ts

use acquire() rather than buy() for UPC sticker acquisition so as to utilise stickers in inventory.

acquire - not buy - UPC stickers

---

src/embezzler.ts
src/yachtzee.ts

We lose significant gains from chaining if we are not able to cover our barfTurns with synth all the way till the end of day.
Previous estimatedTurns() did not factor in organ cleansers, shotglass, borrowed time and chocolates, which massively underestimated the number of turns of synth / organ space we needed to fully cover our run till the end of day.
PR also adds an additional chain-length of 20/25, which fits nicely with pocket wishes (our most expensive buff), allowing us to potentially earn more from a longer chain while also fully benefitting from pocket wish buffs.

Better dynamically-stepped yachtzee

---

package.json
src/dailies.ts
src/index.ts
src/lib.ts
yarn.lock

- Bumped KoLmafia to 4.0.1
- Swapped a call to `myPathId()` to `myPath()` in accordance with `votingBoothInitiatives()` change
- Removed ensuring Van & Duffel's Baleet Shop is a forbidden store
- Changed `checkGitVersion()` to utilize `gitAtHead()`
- Swapped to calling `checkGitVersion()` every time garbo is run
All feedback welcome, thank you for your hard work maintaining this wonderful script.

gitAtHead support

---

src/familiar/freeFightFamiliar.ts
src/familiar/lib.ts
src/familiar/marginalFamiliars.ts

Also use shrub over meat familiar immediately if ELR is on cooldown and its totalFamiliarValue is > meatFamiliarValue (even if we haven't hit our marginal familiar turncount required yet)

Add estimated turns for jellyfish

---

src/familiar/freeFightFamiliar.ts
src/yachtzee/lib.ts

Pyacide encountered issue with Garbo spending turns when launching spikes in the Haunted Kitchen as the Cook was killing the monster before they had a chance to run away (presumably when combined with the spikolodon damage).  
To counter this, have added a optional input to freefightfamiliar options of "allowAttackFamiliars", which filters the familiar list if set to false, and set it for the spike launching fam choice.
An option we might want to also consider if moving the default location to a slightly higher ML area just to ensure the 35 dmg doesnt kill them?

Add option to not allow attacking Familiars when choosing Free Fight Fam

---

src/combat.ts

If we have spacejellyfish as our active familiar, and Macro.familiarActions() is used, attempt to extract jelly

Add Space Jellyfish to familiar actions

---

src/fights.ts

Reverts Loathing-Associates-Scripting-Society/garbage-collector#1083
The Hidden Temple is not a 100% combat zone, and we do not currently have any handling for running +combat or for handling the noncombats. This feature is still welcome, but will need support for those issues to be merged again

Revert "Add stone wool as a possible item steal zone"

---

src/barfTurn.ts

If you encounter an unsuccessful turn for whatever reason, the next will claim to have unexpectedly spent a turn:
Example:
Combat 1: miss sausage goblin
Prints:
```
> We expected to do Guaranteed Kramco, but failed!
> We unexpectedly spent a turn doing Guaranteed Kramco!
```
Combat 2: cast spit acid
Prints:
```
> We unexpectedly spent a turn doing Spit Acid!
```
This fixes the second warning because Spit Acid did not actually cost a turn, the previous combat did.

Cache turn count inside the barf turn loop to prevent false positives

---

src/combat.ts
src/index.ts

The property "olfactedMonster" is not reset on ascension, so we're not currently casting olfaction if we're ascending and not casting olfaction on something else (ie glooping)

Fix olfaction

---

mafia/data/garbo_help.json
src/index.ts
src/lib.ts
src/session.ts

Only change currently is to instead use historical price rather than getSalePrice if the prices are less than a week old, for only items that will be sold.

Add `quick` arg to sacrifice optimal behaviors for quicker execution

---

src/outfit.ts

With hobo monkey, and at current smithsness prices, latte beats Half a purse at embezzlers (and barf) even up to weight 215 hobo monkey
(Smithsness cost is ~48 mpa, so on embezzlers with boombox we gain 157mpa with the 20% meat over latte, so we need 15.3% meat from the 5 familiar weight to beat it, which is the case all the way up to a 215lb hobo monkey)
Ideally we could calculate the value of Half A Purse vs the cost of smithsness, but this is just a quick fix based on current prices similar to what we do with Cheengs.
There is also currently a bug with maximizer (see discord in garbo channel) where it will not currently value the half a purse more than latte anyway, so it uses smithsness but does not equip the purse

Add check for hobo monkey along with robort

---

src/diet.ts
src/fights.ts

Noticed garbo get gingerbread cigarettes over high end ginger wine. Apparently next best consumable was dreadsylvanian grimlet, despite not being of level to drink one of those. Hence, adding in option to restrict BestCOnsumable to items you can currently drink based on level requirement

add option to restrict bestConsumable by levelreq

---

mafia/data/garbo_help.json

NEP is a popular farming and leveling zone, there's a pretty good chance someone might run nobarf then expect to adventure in NEP. This will give us something to point at and say "hey you should read the manual, don't complain".

Remind users that nobarf may close NEP

---

src/fights.ts
src/index.ts
src/lib.ts
src/mood.ts

So the implementation is pretty simple (just use the buff extenders before we start running barf if we didn't use them during embezzlers)
But I'm unsure of where the function should live (if it even should?) my guess was we didn't just want just the raw code in index.ts
My suspicion is that the way I set it up (function living in lib.ts) is probably incorrect because it requires an import from clan.ts.
Perhaps it should be put in mood.ts instead?

Use buff extenders even without embezzlers

---

src/barfTurn.ts
src/combat.ts
src/embezzler.ts
src/extrovermectin.ts
src/fights.ts
src/post.ts
src/wanderer/index.ts
src/yachtzee/fishy.ts
src/yachtzee/index.ts
src/yachtzee/lib.ts
webpack.config.js

Reparsing garbo-combat.js every non-autoattack adventure takes unnecessary CPU. This approach should cover all cases; it's basically what grimoire does, and we could easily switch from this to full grimoireization.

Use writeCcs instead of garbo-combat.js.

---

src/fights.ts

I noticed that I was always leaving 1 free fight on the table. That was because I didn't have a Pocket Professor. This PR fixes that for those of us without one. Thanks Rever for giving me the code for the fix.

Do all NEP free fights if no Pocket Professor

---

src/fights.ts
src/tasks/daily.ts

Over a long aftercore, you can pick up one of each of the training scrolls from the snojo. Do so.
Implementation is casual, and assumes the user isn't changing the options themselves. It finishes in Moxie, like before.

Get training scrolls from snojo

---

src/combat.ts

While this is a bandaid fix to the Extract Jelly bug, it is also consistent with startCombat() which also does Sing Along before familiar actions. Unfortunately, if the user has a jellyfish but no boombox (a rare Guy I'm assuming), this fix does nothing for them.

Try singing along as the first combat action

---

README.md
src/combat.ts

Stasising for 20 rounds can drastically increase how long garbo takes to run for incremental gains. In quick mode, don't.
Some of the causes for 20 round stasis are questionable -- I think BittyCar only happens after the first round, and many crown / bjorn drops only in the first 3 rounds -- but I left them as they were.

feat: if quick mode enabled, don't stasis for as long

---

package.json
src/familiar/constantValueFamiliars.ts
src/familiar/dropFamiliars.ts
src/fights.ts
yarn.lock

Add Rockin' Robin, Optimistic Candle, Garbage Fire, Shorter-Order Cook and Sheep. Crash the wool market!
Not certain expected is in the right format but it should be close.
Don't know how to get the blue plate checked (and later the cigar, after how it affects drops gets spaded). One possibility is we always assume you're equipping it and just buy it if necessary. That's probably simplest.
The XO Skeleton is another interesting one that could be added, but it doesn't really fit with the existing framework: it drops both Xs and Os, roughly 9 turns each, overlapping. You could approximate it with X + O / 2 every 4.5 turns, but that's not quite right.

More drop familiars

---

src/index.ts
src/tasks/dailyItems.ts

Drafted because it is untested rn; not cutting a new eslint-plugin-libram until after the new path, I think

SIT course catalogue support

---

src/post/index.ts
src/wanderer/lib.ts

Since every subsequent combat will be a forced noncombat, we can closet it.

Handle funky junk keys

---

src/tasks/daily.ts

If there is a "piece of driftwood" in inventory and it can be used to grant temporary access to Comb the Beach, then use it.

Use `driftwood beach comb` for buff and free walks

---

src/index.ts
src/wanderer/lib.ts

This allows us to wander in locations that are safe to backup in because all NCs in the area are skippable or lead to a combat.
Unfortunately I cannot test this within normal garbo, I do not have guzzlr. I have however been running essentially this with a custom garbo that does Doc Bag locations and has been working well.
I'm not 100% happy the way I'm setting the choice option properties right now (Just always setting them in main), but I have yet to come up with a better answer.
**Locations that we may also consider later for long aftercore (or if there is some way to know whether we have already encountered one-time adventures this ascension):**
- The Sleazy Back Alley
- The Haunted Pantry
- The Outskirts of Cobb's Knob 
**Locations we may consider with additional handling:**
- Madness …

Backup safe list

---

src/wanderer/lib.ts

the code said 6 was the right choice but it is actually 2, see #509

fixing cobb's knob barracks choice

---

src/wanderer/lib.ts

The Whole Kingdom combat resulting from the noncombat can't be instakilled and the noncombat is not skippable otherwise it seems.

Don't wander at Professor Jacking's Huge-A-Ma-tron

---

src/index.ts
src/tasks/daily.ts

This just picks up the ChibiChanged buff (5 fam weight) during our daily tasks if it's available.
It does not do any caretaking of the Chibibuddy, so it'll only last a few days, but even if it just died it still gives you 5 turns of the buff.
There isn't any mafia support of chibibuddy currently, so this probably isn't very performant. It's been working good for me during eternal aftercore though.
Thanks to phred for the names ([Discord post](https://discord.com/channels/466605739838930955/864070665615179786/1042932371902693476)) but if it's too "cute" we can use some generic name? Or possibly just use the auto-generated name with an empty field.
This won't pick up the buff if you already had it from manually doing it pre-rollover, but I couldn't come up with a better `completed:` without …

1st phase Chibibuddy implementation

---

src/fights.ts

This PR updates the pygmy bowler options to use the new `spec` based outfit that was introduced in 05ea195073a1887dffe40399b79b858e5e5feb8e

Fix pygmy bowling saber use

---

src/yachtzee/familiar.ts

I was poking around this code the other day and noticed a couple of minor issues.
Firstly the `famWt` calculation was using the currently equipped familiars weight rather than the familiars being checked.
Secondly the 3rd parameter being passed to `numericModifier()` is, according to the mafia wiki should be the buffed weight, excluding equipment as equipment is provided as the 4th parameter (see https://wiki.kolmafia.us/index.php/Numeric_modifier ).
I've tested this on subsequent days coming out of Normal Standard runs & immediately running garbo after breaking prism & emptying hagnks.
Before
```
> Familiar bonus meat%:
> Urchin Urchin (569.68%)
> Hobo Monkey (562.56%)
> Cat Burglar (467.83%)
> Leprechaun (467.83%)
> Jitterbug (467.83%)
> Casagnova Gnome (467.83%)
> Hunchbacked Minion …
```

2 small fixes to Yachtzee! familiar weight calcs

---

src/diet.ts
src/yachtzee/diet.ts

Benefits: generally it's better to consume these items immediately coming out of an ascension rather than at a later date.
Drawbacks: users whose preferences are out of sync will try and fail to eat the pizzas resulting in at least one incorrect diet calculation.

Change pizza and calzone of legend into regular diet options & don't prevent pilsners and pizza until ascending

---

src/index.ts

We can remove the disable-next-line once the eslint plugin is updated

preventEquip Amulet of Eternal Darkness

---

src/diet.ts
src/yachtzee/diet.ts

This is simple to add for general garbo, but yachtzee is a bit more arcane for me. Hopefully I did it correctly, I just left the max price of them at 60k, same as boris bread and radishes
(Max price for embezzlers would be something under 40k, and something under 80k for yachtzee depending on user VoA)
I don't know if the supply of these can meet demand currently, but people might consider zapping race car reds and lambadas. So essentially people with the beer garden are making one per week if I understand that correctly.
Perhaps that was a reason these weren't implemented before though. to not mess with the supply of those.

Greedy dog for diet

---

src/outfit/embezzler.ts

setLocation alone won't work here. We should consider adding location ID or name to the key we use for outfit caching in libram.

Categorically ban cheap sunglasses from embezzler outfit

---

mafia/dependencies.txt

Recent modifier changes in https://github.com/kolmafia/kolmafia/pull/1815 broke Bastille and Gain; point to my forks instead until the PRs are merged so that users don't have to pull scripts manually.

fix: use my forks of Ezandora's scripts to fix modifier issues

---

src/familiar/meatFamiliar.ts

When we fight embezzlers while overdrunk, we don't use the wineglass so there's no reason to prioritize the tot. And tot already exists as a `constantValueFamiliar` so there's no reason to add it as a special case for barf.

Remove tot special casing from meatFamiliar

---

src/barfTurn.ts
src/embezzler.ts
src/fights.ts

Noticed I was having leftover forced NC's, we should probably track when a Yachtzee wasn't successful.
Anyways, I didn't meet the stat requirements for "aerated diving helmet" but the script didn't recognize that when the maximizer failed. This fixes the attempt to use equipment I couldn't wear.

Dont try to use water breathing equipment we can't equip

---

package.json
src/diet.ts
src/embezzler.ts
src/potions.ts
src/resources/index.ts
src/resources/scepter.ts
src/tasks/dailyItems.ts
src/yachtzee/diet.ts
src/yachtzee/fishy.ts
src/yachtzee/lib.ts
yarn.lock

TO DO:
- ~~find a way to add roller coaster to diet and yachtzee diet without circular imports~~
- ~~cast mountain specifically pre-embezzler~~removed
- ~~add clover to embezzlers~~ ~~and yachtzee~~,
- after free fight revamp: add free fights
- probably make us have quest-generating functions instead of static lists

First stage of scepter support

---

src/combat.ts

Since you are much more likely to fight 10 of these in a row, and works for a broader set of user usecases.

Cast Recall Facts on Embezzlers instead

---

src/yachtzee/index.ts

interrupting yachtzee  with the "interrupt garbo" problem aborts before we update _stenchJellyUsed or _stenchJellyChargeTarget, which sucks!

do postCombatActions _after_ processing yachtzee information

---

.github/workflows/build.yml
package.json
tsconfig.json

`tsc` is already configured with `noEmit`, so it can be run straight.
Add `skipLibCheck` as otherwise you get errors with duplicate definitions in `react` and `react-dom`.

feat: actually check types when running CI test

---

package.json
src/garboWanderer.ts
src/index.ts
src/libgarbo/wanderer/lib.ts
yarn.lock

while I can use the `factType` proxy record in the switch--and doing so protects me from having to count pocket wish and tatter drops--wanting to check quantities of items and effects forces me to use the `itemFact`, `numericFact`, and `effectFact` functions instead of proxy records. Which is fine, but a little awkward given that I have to pass in the seed.

bofa value

---

src/embezzler/fights.ts

The banished monsters preference isn't updated until you banish another monster. Because of this, the fluffy bunny can be present in the list of banished monsters after a used banish has expired.

fix: check whether bunny is still banished instead of was ever banished

---

packages/garbo/src/tasks/barfTurn.ts

This was causing a call at script start, as well as extra calls for each wandering embezzler

Fix embezzler choice causing a wanderer call

---

.github/workflows/garbo.yml

Fixes warning in ci
`YN0050: The --frozen-lockfile option is deprecated; use --immutable and/or --immutable-cache instead`

--frozen-lockfile > --immutable --immutable-cache

---

packages/eslint-config-garbo/index.js
packages/garbo/src/familiar/freeFightFamiliar.ts
packages/garbo/src/garboWanderer.ts

Not sure what actually happened to the user in #1645 but this is good practice anyway. If we want to flag selecting no familiar as an error we should do so explicitly, not via a TypeError.
- Add eslint rule to enforce initial value for reducers
- Fix resulting linting errors

Enforce initialValue for reducers to avoid unexpected behaviour

---

packages/garbo/src/embezzler/fights.ts
packages/garbo/src/fights.ts
packages/garbo/src/resources/fax.ts

Try and get a photocopied monster before embezzlers are started rather than during execution
Use faxbot rather than messaging cheesefax directly (this is the same logic as autoscend)

Prevent faxbox abort if network is down

---

packages/garbo/src/tasks/daily.ts

If all you do is talk with the guild to get the quest that unlocks forest, other visitUrls to locations there will result in "You can't get there!"
Hitting woods.php seems to register the actual unlock

Register forest unlock

---

packages/garbo/src/fights.ts

technically this is a waste of meat buffs, but atm garbo is never getting UMD at all which is more of a loss. When the yatchzee code is cleaned up it should defer doing this until the post-barf turns if UMD is available
I haven't tested this yet my week reset isn't up

UMD price check needs to compare against cap

---

packages/garbo/src/embezzler/fights.ts

If you had a non-Embezzler copied monster and both a Rain-doh and a putty, the available amount was wrong, e.g.
```
_raindohCopiesMade: 5
rainDohMonster: deadly venomtrout
spookyPuttyCopiesMade: 1
spookyPuttyMonster: 
```
gives 4 remaining, but it should be 0.
I think the new logic is right, but I haven't tested it extensively.

fix: putty / raindoh remaining count

---

packages/garbo/src/resources/synthesis.ts

Currently, sugar chapeau and sugar shirt tend to build up in quantity because the distribution of untradeable candies is biased towards some item ids.
Additionally, add peanut brittle shield to the list.

Synthesize untradeable candies with tradeable ones, not just in pairs

---

packages/garbo/src/resources/candyMap.ts

This should bypass it for now. Manually set the property just in case because it doesn't seem to work.

Workaround for candymap redirecting to a choice adventure

---

packages/garbo/src/index.ts

This change will reorder steps:
1) Show version
2) Show help
3) Abort if stuck in a choice or in combat
4) Update mall prices
Ideally version and help should work even if logged out and shouldn't depend on game state to work.
Mall prices should be checked after ensuring not stuck in a choice or combat, because the mall can't be accessed in either state.

Reorder main function

---

packages/garbo/build.mts
packages/garbo/src/lib.ts

gitAtHead() doesn't fetch so it may not be accurate
will look something like this
```
> garbo version
Using adventure value 6200.
Local Version: c83d4e239be2bdf7b2f9690323d1aa0f197bfd60 (built from main@e76719a795c515a7c48f9971da1aa91e3e3a6e9b)
Release Version: 13ab1bc57868edc5d438e721183f24b81f56cd2f
Garbo is out of date. Please run 'git update'!
> git update
...
> garbo version
Using adventure value 6200.
Local Version: 13ab1bc57868edc5d438e721183f24b81f56cd2f (built from main@c860fa9446cb1920827c2ae0567fe21af92972f8)
Garbo is up to date!
```

check github for update

---

packages/garbo/src/fights.ts
packages/garbo/src/garboValue.ts
packages/garbo/src/resources/autumnaton.ts
packages/garbo/src/tasks/dailyItems.ts
packages/garbo/src/tasks/freeFight.ts

Left it in the garbolib stuff at the moment because it may be useful to some future script, but because we do a `mallPrices("allitems")` there's no need for it for us.

no more historical price checks

---

packages/garbo/src/resources/worksheds.ts

I don't believe this fixes the underlying issue, but it should prevent garbo encountering a non-stop loop.
What it does is if the trainset was not configured, but is still configurable, set the last trainset configured counter to 39 trainset positions ago.
This should then tell garbo that we can configure the trainset in 1 train station instead of now.

A partial fix for #1702

---

packages/eslint-config-garbo/index.js
packages/garbo/src/tasks/dailyItems.ts

Maybe we should just extend `@typescript-eslint/strict`?

disallow non-null assertions

---

packages/garbo/src/resources/scepter.ts

Currently if you cast the TODAY skill while in run, Mafia flags the _augXCast as true but does not flag the _augTodayCast as true. As a result, if the run ends in the same day and garbo is run, shouldAugustCast considers the skill to be castable when it's already been cast for the day and is actually not castable. This should fix it (I think)

August Scepter fix

---

packages/garbo-lib/src/wanderer/index.ts

90 is Curtains, and skip is choice 3, and Quartet is 106.
This seems to have been in place for a long time without being reported, but I think this is the expected behaviour.

fix: quartet choice is 106, not 90

---

packages/garbo/src/resources/fax.ts

Aside from it being a good idea for multiple people using fax at the same time and thus always interfering with each other, it'd also help with OnlyFax now telling you off if you're spamming it with requests.

With every failed fax, wait 2 seconds longer

---

packages/garbo/src/combat.ts
packages/garbo/src/embezzler/lib.ts
packages/garbo/src/embezzler/staging.ts
packages/garbo/src/fights.ts
packages/garbo/src/resources/extrovermectin.ts
packages/garbo/src/tasks/barfTurn.ts

Changes this error blob from
```JavaScript exception: Combat exception! Last macro error: Macro Aborted ("abort "Expected Knob Goblin Embezzler but encountered something else.""). Exception KoLmafia error: You're on your own, partner. (Macro Aborted ("abort "Expected Knob Goblin Embezzler but encountered something else."")).```
to
```JavaScript exception: Combat exception! Last macro error: Macro Aborted ("abort "Macro for Macrometeorite expected Knob Goblin Embezzler but encountered something else.""). Exception KoLmafia error: You're on your own, partner. (Macro Aborted ("abort "Macro for Macrometeorite expected Knob Goblin Embezzler but encountered something else."")).```
Sure, with context you'll eventually figure it out. But this makes it easier to figure out what the script was …

Actually name what action the macro was created for

---

packages/garbo/src/combat.ts
packages/garbo/src/outfit/dropsgear.ts

Unsure if the math will ever work out for this especially since it takes two slots but worth calculating. Pretty much limited to only seal clubbers as otherwise it is difficult to crit when the weapon and off-hand slots are used.
The wiki drop rates I sourced from are probably slightly off but all that really matters here is what appears to be a 1% combined drop rate for fancy chocolate and jawbruisers

Support bindlestocking crit drops

---

packages/garbo/src/tasks/post/index.ts

Sometimes mafia doesn't remove autumn-aton from inventory after sending it out. This check should avoid that.

Check to avoid autumnaton maxBy on empty array error

---

packages/garbo/src/index.ts

- **Check to avoid autumnaton maxBy on empty array error (#1972)**
- **use purple candle in meatKill too (#1973)**
- **remove jill from bestFairy (#1974)**
- **Allow arbitrarily high voa for nobarf**

Allow high vOA for nobarf

---

packages/garbo/src/combat.ts

Little red book is another repeatable deleveler so may as well.
Apparently I'm not the only That Guy who lacks Northern Explosion, and the current `.kill()` logic for muscle > mysticality has LTS come up ahead of Saucegeyser, which is a problem for mimes. Try to circumvent that.

Add little red book, skip LTS for mimes

---

packages/garbo/src/tasks/engine.ts

we rely on `postCombatActions` to `safeInterrupt` during many of our non-grimoirized sections of code; this will ensure that we can `safeInterrupt` even if we never select a task to execute.

move `safeInterrupt` to `available`

---

packages/garbo/src/combat.ts
packages/garbo/src/potions.ts
packages/garbo/src/resources/autumnaton.ts
packages/garbo/src/resources/mayam.ts

Minor performance improvement, but one all the same.

use `flatMap(...)` over `map(...).flat()`

---

packages/garbo/src/combat.ts

I've noticed a significant slowdown this past week or so, looks like `copyTargetCount` includes a ponder pagehit and a pagehit examining mimic eggs. The former is cached and will happen at most once per combat (still v unnecessary) but the latter isn't and will potentially get hit a lot as a result. This'll make us not call `copyTargetCount` every barfTurn

only try to emit drones if we have goose up

---

packages/garbo/src/tasks/barfTurn.ts

I feel like garbo has gotten way slower, besides just diet, and I assume this is the culprit.

only run `meatMood` every 11 turns, for speed reasons

---

packages/garbo/src/config.ts
packages/garbo/src/index.ts
packages/garbo/src/tasks/post/worksheds.ts

There's no point keeping it active as visiting it once gets you the items, which happens when you visit the workshed, which is done when Mafia tries to figure out what workshed you have.
Ignore libram/verify-constants because TakerSpace isn't in there yet.

feat: support workshed=takerspace

---

packages/garbo/src/tasks/dailyItems.ts
packages/garbo/src/tasks/freeFight.ts

Simplistic version just to use the free fights for now

First pass CyberRealm

---

packages/garbo/src/index.ts
packages/garbo/src/lib.ts
packages/garbo/static/dependencies.txt

This lets us avoid redundant `mallPrices` calls across other scripts like crimbo, freecandy, etc

switch to using external `mall-check` script

---

packages/garbo/src/tasks/dailyItems.ts

I have a cached value here so that we aren't running the calculation every time to check the completion, but we still need to be able to get different candies each re-run, so we also use the non-cached version

Deviled candy

---

packages/garbo/src/familiar/lib.ts
packages/garbo/src/tasks/barfTurn.ts
packages/garbo/src/tasks/daily.ts
packages/garbo/src/tasks/freeFight.ts

I put acquiring and using a walkie talkie for our `GarboFreeFightTasks` ghosts in our dailies rather than within that task to not explode the ready and completed conditions for the task, and to avoid aborting if the acquire fails during the prepare/acquire step.

Support using walkie talkies for ghosts

---

packages/garbo/src/outfit/dropsgearAccessories.ts

Excavator data has confirmed that the drops are any tradable and discardable potion that is not currently tagged to be under standard restrictions. This can be checked by the "Last Available" modifier for an item being an empty string.

Update bonus for Mr. Cheeng's spectacles to be accurate based on what items can drop

---

packages/garbo/src/tasks/freeEggDonation.ts

To prevent donating near max monsters if status is out of date

Lower max by days since update

---

packages/garbo/src/resources/everfullDarts.ts
packages/garbo/src/tasks/barfTurn.ts

The Everfull Darts task allows using a Spring Shoes runaway if bullseyes aren't guaranteed. Adding the ability to instead use a Roman Candelabra if one doesn't have Spring Shoes.
Also noticed that we wouldn't ever attempt bullseye if our darts level is too high for fear of killing, even if one is guaranteed. Changed that slightly so we'd always attempt a guaranteed bullseye (given there's no risk of accidental death).

Allow Candelabra runaway when throwing darts

---

packages/garbo/src/tasks/freeEggDonation.ts

* take eggnet priority into account for valuation
* delevel / stun monster if it scales or it's stronger than us
* allow using cheap unlimited sources to escape the fight
* don't do any of this logic if no reminisces left
Haven't tested this yet, will after rollover
Should help resolve #2511

egg donation tweaks
