KoLmafia/scripts/garbage-collector/garbo.js
src/index.ts

Use dark horse and preternatural greed demon if available

---

KoLmafia/scripts/garbage-collector/garbo.js
src/diet.ts

Add price cap for octolus oculus

---

KoLmafia/scripts/garbage-collector/garbo.js
src/fights.ts

Don't loop infinitely in snojo

---

KoLmafia/scripts/garbage-collector/garbo.js
src/fights.ts

Use homebrew faxbot that doesn't break stuff

---

KoLmafia/scripts/garbage-collector/garbo-combat.js
KoLmafia/scripts/garbage-collector/garbo.js
src/fights.ts
yarn.lock

Resolves #31 
Also updates yarn lock to reflect garbo version as I've been using package-lock til now, oops

Support replica bat-oomerang

---

.gitignore
src/index.ts

Threw a big try...finally around most of main(), making it revert back to your original setting. I have tested the visitUrls and xpaths, but have not actually tested garbo itself in this state.

Checking the AutoAttack Boss box

---

KoLmafia/scripts/garbage-collector/garbo-combat.js
KoLmafia/scripts/garbage-collector/garbo.js
package-lock.json
package.json
src/index.ts
yarn.lock

The barfTurn function would reconfigure the cape only if both the superhero and wash instructions were not properly set.  The updated code now runs the cape configuration command if either of them are not set to the desired configuration.

Corrected the check for the robot cape configuration.

---

src/index.ts
src/outfit.ts

It doesn't vote for you, but it'll obtain proton quests, fight aforementioned ghosts, and also fight voter monsters. It will not get a proton quest when embezzlers are up, because it just isn't worth it.

ghost and voter support

---

src/fights.ts
src/index.ts

Verify you have access to the forests before trying to get latte
Stop thinking you have NEP access once you finish the quest
Reset garden after barfloop
Resolves #55, resolves #26

latte, NEP, and garden fixes

---

src/outfit.ts

Screege's spectacles give an estimated +180 mpa. I've seen some hemming and hawing over those numbers, but we're currently calling LGR a flat 400 so I think this is safe to call a reasonable estimate.

Add screege

---

src/lib.ts

This should unbreak stuff sorry everyone

edit questStep to account for rejected quest in the NEP

---

src/index.ts

Currently appears only at the top of barfTurn() and inside the backing up while().

add check for beaten up effect at the start of barfturn()

---

src/index.ts

appropriately store the value of the aa boss flag

Checkbox fixes

---

src/index.ts

If valueOfAdventure is < 3500, as is default, this will go poorly, so abort out in that situation

Sanity check valueOfAdventure

---

dependencies.txt

Added canadv to dependencies.txt. It's on SVN--that's not going to be a problem, right?

canadv is a dependency now

---

src/dailies.ts
src/index.ts
src/lib.ts

Sliced up daily tasks, throwing them into their own file to make it look nicer as I prepare to radically expand said tasks
also, threw a visitUrl() in before trying to visit the horsery. Mafia sometimes has trouble after standard runs.

Restructured daily tasks to allow for expansion

---

dependencies.txt
src/dailies.ts

BC Goldman was having trouble with dependencies--I think the URL was written incorrectly. I can't really test this without this being put on release, as far as I'm aware.
Added a have($skill`unaccompanied miner`), in case people don't have the skill unaccompanied miner.

Volcano fixes

---

src/lib.ts

I have thought for literally a full year that they weren't tradeable what's _wrong_ with me

add DRINK ME to zonePotions

---

src/lib.ts

spring loaded Front bumper

---

src/familiar.ts

If you decide this is too intensive to be remotely worth using, that's life! Just wanted to put it on the table.

use horrible array methods to decide the best meatFamiliar()

---

src/dailies.ts
src/fights.ts
src/index.ts
src/lib.ts

After my CS and casual loops, I typically find garbo trying to do the first profchain without enough weight to lecture properly. Now, before each profchain, we'll check whether we've added enough weight to do more lectures. If not, we'll revert to a regular meat familiar and a regular meat outfit, and still mark that particular profchain as complete.

Profchain only if you can

---

src/fights.ts

VYKEA, along with some familiars, deal enough passive damage to kill these monsters. So let's just get it over with.

remove sing along from ninja macros

---

src/dailies.ts
src/fights.ts
src/index.ts
src/lib.ts
src/outfit.ts

Made an additional function for choice adventures that accepts a map input. Turns out not to be that much easier than just defining the property objects.
Resolves #35

Property wrapper

---

src/index.ts

Added code to grab the skill Furious Wallop if we're a seal clubber and have guild access.  I've placed it here since the next bit of code checks to see if we have the skill.

Obtain Furious Wallop if we don't currently have it.

---

src/dailies.ts

Grabbing a cheap hat for the hatter buff.

Added code to grab a hat for the hatter buff.

---

src/fights.ts

Use an embezzler copy to wink at / fire a badly romantic arrow at them for yet more (unpredictable) embezzler copies

Add Winking / Arrowing Embezzlers

---

src/index.ts
src/lib.ts
src/outfit.ts
src/stash.ts

currently a draft because it uses a bad alternate version of getFoldGroup--something will need to update before we can use getFoldGroup for rhino reasons

get foldables from stash

---

src/dailies.ts
src/index.ts
src/lib.ts

use macrometeors and replace: enemies to farm stench jelly

---

src/dailies.ts
src/index.ts

gaze daily

---

src/fights.ts

add garbage sticker bonus equip to drunk pygmy free fights

---

src/index.ts

this beast must be vanquished once and for all

add papier-mitre to maximizer banlist

---

.github/workflows/build.yml
mafia/data/garbo_settings.txt
mafia/relay/relay_garbo.ash

Create config ui, deploy appropriately.

---

package.json
src/fights.ts
yarn.lock

Accidentally attached upgrading the kolmafia package to this--sorry!
We previously had a lot of code for starting the NEP quest properly, but only in the actual NEP section--most of the time we skip the quest during the thesis section. Now, everything should work out fine.

Initialize nep during thesis

---

src/fights.ts

This _should_ solve Manny's weird problem

add more copies to secondChainMacro to reduce pocket wish reliance

---

src/diet.ts

checking hagnk's for diet things so it doesn't buy from mall unnecessarily

add takeStorage to diet acquire function

---

src/lib.ts

- Add V for Vivala mask banish as free run
- Add stinky cheese eye banish as free run
- Add navel ring of navel gazing \ Greatest American Pants 3 free runs
- Fix banderRun prep check if you also have boots and are unable to get ode

Add more banish\free run sources

---

src/lib.ts

Since you can malus 5 nuggets in to 1 wad as a muscle class. Even if you aren't one now, you can next time you are.

Consider elemental fairies for bjorn at 1/5th wad value

---

src/diet.ts

cease breaking when we can't get a mojo filter

---

src/dailies.ts

Hopefully now we won't buy 123,456 meat bloody noras

changing robort drinks from buy() to retrieveItem()

---

package.json
yarn.lock

I can only pray this is the last time

Upgrade libram for guzzlr reasons, again

---

src/combat.ts

Probably a really minor optimization, but it's not like it gets used otherwise

Add feel nostalgic support

---

src/dailies.ts

This has been tested a little bit, but is behaving weirdly in the CLI--I'll have to test it more tomorrow

refresh latte information before embarking on journey

---

package.json
src/relay/App.tsx
src/relay/components/Setting.tsx
src/relay/css/App.css
src/relay/index.tsx
src/relay_garbo.ts
webpack.config.js
yarn.lock

Use react for rendering the relay browser

Use react for relay browser

---

src/index.ts

no drunk ghosts or votes

---

src/dailies.ts
src/diet.ts
src/fights.ts
src/globalvars.ts
src/index.ts
src/outfit.ts
src/potions.ts

Reverts Loathing-Associates-Scripting-Society/garbage-collector#290
@Rinn has encountered some sort of bug that may be related to it; I want to go to bed, and cannot investigate till morning, so we should aim to be safe.

Revert "Better adventure estimates"

---

src/combat.ts
src/fights.ts

- Macro.tryCopier() checks various conditions on whether or not a copier item or skill should be used
- Add support for Rain-Doh black box
- Use a spooky putty monster if it is invalid after ascending
Ran two days and it seems to be working correctly.

Add Rain-Doh black box, add Macro.tryCopier() function

---

src/lib.ts

@phillammon please take a gander and see if anything else dumb is happening

make DMT choice work properly

---

src/familiar.ts

I'm not sure if the expected array is correct or not.

Add astral badger to rotatingFamiliars

---

src/mood.ts

+lbs hippy arena buff

---

src/combat.ts

Mafia doesn't actually update _latteMonster when the olfact expires. Data for when it expires is stored in counters instead. So we check those now.

Use latte olfact again when it expires

---

package.json
src/dailies.ts
src/diet.ts
src/fights.ts
src/index.ts
src/lib.ts
yarn.lock

still in testing, but I expect it to work

Upgrade libram and use PropertyManager

---

src/dailies.ts
src/outfit.ts

Set Snow Suit to nose for drops & +item

---

src/fights.ts

Display the potential remaining count when prompting for embezzler wish.

Show potential on embezzler wish prompt

---

src/bjorn.ts
src/dailies.ts
src/lib.ts
src/outfit.ts

Built off of #331, so that should be merged first
Flower drops are weird, I got the first 4 relatively quick than the 5th took a lot more turns to get (wiki speculates the drop rate falls off), so I added in a pretty aggressive degeneration of the drop rate and floor it at 1% after 5 drops so garbo won't get stuck with using it over something better for an extended amount of time.

Mayflower Bouquet drops + sporadic +meat bonus

---

src/index.ts

it messes with bander and boots run counters

never equip smoke ball

---

src/acquire.ts
src/diet.ts

Just replacing two calls to mafia drink with drinkSafe

drinkSafe instead of drink

---

src/index.ts

Chose the version just because that's what I currently have--if there's any reason to pick an earlier one, I guess we can do that

update kolmafia version requirement

---

src/fights.ts

thanks, hgleghe, for the bug report

retrieve glitch season reward

---

src/fights.ts

Use any lick charges you have remaining if you're ascending.

Use shocking lick as a free kill

---

src/fights.ts

Fixes choice option for escaping DMT.  Changes to 6 from incorrect 5

Corrects escape DMT

---

src/mood.ts

Adds in The Legendary Beat to one-day use items/buffs

Add in The Legendary Beat

---

src/dailies.ts
src/fights.ts
src/index.ts
src/outfit.ts

@Rinn rebased for you, but I want to make sure that's cool; takes the place of #373

Rebased freeruns

---

src/diet.ts

Calculate expected value of class chocolates. Uses the one with the highest expected value if it's greater than zero.

Refactor class-chocolates logic

---

src/diet.ts

Labels are way more readable than 2-d arrays.

Small code clarity update for class chocolates

---

src/fights.ts

#204
Could make this more complex and get more expensive items if you have a ton of sprinkles, but this is a good start.

Free run for gingerbread cigarettes

---

src/combat.ts

Use if adventures remaining is less than 150 on any digitized embezzlers for the +lbs.

Use meteor shower on embezzlers near end of day

---

src/familiar.ts

Also use saleValue instead of mallPrice, have instead of haveFamiliar

More item dropping familiars

---

src/fights.ts

Add in Bag O' Tricks

---

src/combat.ts
src/lib.ts
src/outfit.ts

#379
@docrostov 
I recognize that this is pretty inelegant, but I think the core conceit of what I'm aiming for is good; I'd love advice on how to do that in a less ugly and terrible way. I couldn't use a standard destructuring method because a lot of the fields in maximizeOptions are optional

restructure freeFightOutfit; add cloake to startCombat() and freeFightOutfit

---

src/dailies.ts

Handle beaten up from mining

---

src/diet.ts

use universal seasoning

---

src/fights.ts

Also adds megawoots quest but doesn't have the free kill logic to complete it yet.

Add trash and DJ NEP quests.

---

src/index.ts

set autoSatisfyWithStash

---

src/clan.ts

Try to run away if stuck in a fight.

---

src/fights.ts

Just removing unnecessary comments now

Enable eslint libram checks for fire extinguisher

---

src/combat.ts
src/dailies.ts
src/diet.ts
src/embezzler.ts
src/fights.ts
src/globalvars.ts
src/index.ts
src/lib.ts
src/outfit.ts
src/potions.ts
yarn.lock

Since pasta thralls can do damage they make stasis free fights like the fire extinguisher more difficult to handle.

Move Pasta Thralls after free fights

---

src/fights.ts

I'm not even really sure if this is worth doing but maybe someone will get extremely lucky and get an ultra-rare.

Free run from BASIC Elemental with summon mayfly swarm

---

src/bjorn.ts
src/dailies.ts
src/diet.ts
src/familiar.ts
src/fights.ts
src/lib.ts
src/outfit.ts

Not using libram's findRun because we reserve some banishes for drunk pygmies, and we can't do that with the libram version

more more stuff to libram

---

src/index.ts

Placed in index.ts because there's no single zone where this can occur

Add support for halloweiner choice adventures

---

mafia/data/garbo_settings.json
src/clan.ts

Option to disable borrowing from clan stashes

---

src/index.ts

Reverts Loathing-Associates-Scripting-Society/garbage-collector#486

Revert "don't use mafia voter counter"

---

src/fights.ts

Unfortunately there's a semi-rare adventure here. Maybe this isn't worth doing?

Try to get rusty hedge trimmers from the twin peak

---

src/dailies.ts

I had to `toMonster` the `get("_voteMonsterX")`s, which isn't very pretty. For this, I apologize.

votingMonsterPriority reconfigured

---

src/fights.ts

Fix ice sculpture calculation

---

src/index.ts

Also move the help command parsing logic.

End garbo on invalid argument passed.

---

src/index.ts
src/lib.ts

Allows you to specify a negative number of turns to stop when you only have that many remaining.

Allow saving a fixed number of turns.

---

src/fights.ts
src/lib.ts

Reverts Loathing-Associates-Scripting-Society/garbage-collector#539

Revert "burn librams before using PYEC and LTC"

---

src/wanderer.ts

One concern I have about this is there's a second version of choice 884 that appears when all babies are there. But I'm going to go ahead and say that you'll only encounter that if you really try to make that happen.

support Chasin Babies

---

src/bjorn.ts
src/lib.ts
src/outfit.ts

Reverts Loathing-Associates-Scripting-Society/garbage-collector#540

Revert "start using libram's bjorn logic"

---

src/fights.ts
src/lib.ts

Need to wait for an updated libram again :c

Burn baby burn it's the libram inferno

---

src/diet.ts
src/lib.ts
src/mood.ts
src/synthesis.ts

This is untested, and hasn't been touched in a while; creating as draft.
@gausie is it worth adding this synth code to Libram?

Add synth code to use up untradeables.

---

src/combat.ts

right now, we only ever try to Become a Wolf in startCombat(), which I don't think gets called as often as we'd like.

use Become a Wolf in kill() and in stasis

---

src/combat.ts

Add feel superior to .kill(), so people can get pvp fights.
It costs 0 MP, so might as well.

Use feel superior if appropriate

---

src/wanderer.ts

adding a choice for hidden apartment; i think this should work?

adding a choice for apartment issue

---

src/embezzler.ts
src/fights.ts
src/lib.ts

I had a slightly different approach I wanted to try for this, and thus didn't feel it was appropriate to directly piggyback atop #530. Still, it is fruit from the same tree, and a vast majority of this comes from bman's juicy brain.

Setup KGEs after prompting user to use wish (mostly stolen from BMan)

---

src/acquire.ts
src/index.ts

You might want to wait a day or two to squoosh, since this is today's revision.

update mafia revision

---

src/outfit.ts

Turns out the cli command just wants 'latte refill pumpkin' so this is easy.

fix latte ingredient

---

src/wanderer.ts

Reverts Loathing-Associates-Scripting-Society/garbage-collector#591

Revert "Wanderer refactor"

---

src/fights.ts

Free kills from the carnivorous potted plant are even better than free runs here so we get extra value out of equipping it in these locations.

Add carnivorous potted plant for gingerbread city and the menagerie

---

src/fights.ts

Right now, once you have 100 pill-pairs, you pick up 1 pill-pair per day, which feels suboptimal relative to getting them in chunks. so this chunks 'em!

store pill quantities at start, so we only get pills in chunks rather than one a day

---

src/combat.ts
src/fights.ts
src/index.ts

Reverts Loathing-Associates-Scripting-Society/garbage-collector#651

Revert "shore up holiday wanderer support"

---

src/embezzler.ts
src/extrovermectin.ts
src/fights.ts

Also more accurately count the number of embezzlers you will fight from being gregarious

Reset the orb by visiting the shore

---

src/diet.ts

Add support for speakeasy booze

Support shotglass even if your organs are already full.

---

.eslintrc.json
src/dailies.ts
src/dropsgear.ts
src/embezzler.ts
src/extrovermectin.ts
src/fights.ts
src/index.ts
src/lib.ts
src/mood.ts
src/outfit.ts
src/post.ts
webpack.config.js

Requires a space after every comment and braces around an if that breaks to multiple lines.

Enforce spaced-comment and multiline if with eslint.

---

src/extrovermectin.ts

This reduces market pressure for users who don't own the crystal ball.

If you don't own a  crystal ball then you don't need long banishes to initialize dire warren

---

package.json
src/embezzler.ts
src/extrovermectin.ts
src/fights.ts
src/lib.ts
yarn.lock

Free kills will come in another PR

Use libram free run ActionSource

---

src/combat.ts
src/dropsgear.ts
src/index.ts
yarn.lock

This should be ready as per https://github.com/kolmafia/kolmafia/pull/464, but I want to test it again tomorrow because I'm a scared little man. Also I'll need to bump mafia version again.

upgrade eslint plugin; add CMG as bonusEquip

---

src/embezzler.ts
src/familiar.ts
src/fights.ts
src/wanderer.ts

Primary goal of this PR is to
a) make fights.ts more streamlined and to refer to specific behaviors of an EmbezzlerFight rather than referring to the fight by name
b) describe the behavior of an embezzler fight with a set of options with reasonable defaults to make it clear what behavior is nonstandard for a given fight
c) reduce clutter and duplication of code so future changes will be less invasive

Clean up embezzler.ts and fights.ts to be more straight forward

---

src/index.ts

Includes both the Spooky Putty sheet update and the fix for infinitely doubling Squint/Swagger/Bend Hell.

Bump minimum kolmafia revision to r26200

---

src/combat.ts
src/embezzler.ts

- Actually use backup against monsters when appropriate
- Verify orb predictions with ponder

Holiday wanderers ii

---

src/fights.ts

Only olfact if we have more hugs and kisses
Save 2 olfactions for extrovermectin and barf mountain
Don't count fire extinguisher charges if you don't own the iotm

Polar Vortex/XO-Skeleton Improvements

---

src/clan.ts
src/index.ts

return previously-stolen stash items

---

src/dailies.ts

- Use retrievePrice to determine the best volcano item
- Make log message for fused fuse a little more informative

use retrievePrice to decide best volcano item to get

---

package.json
src/fights.ts
yarn.lock

Once our goose is fully charged, we'll want to use it only on one fight, where we'll want to use our meat skill before discharging it. Some fights don't let us pick our own macros, so we don't want to use the goose for these fights if the goose is primed.

create canOverrideMacro option for freeFights

---

src/mood.ts

- removes deprecated shrugging code from freeFightMood
- fixes flaskful of hollow logic
- removes synth code from meatMood
- fixes rounding of KGBriefcase

mood cleanup

---

src/embezzler.ts

Relevant libram code here:
https://github.com/Loathing-Associates-Scripting-Society/libram/blob/main/src/counter.ts

Switch over to Libram counter stuff

---

src/dropsgear.ts
src/fights.ts
src/lib.ts
src/potions.ts

- Cap doubled value at the price of the potion itself
- Make sure we aren't set to barf during potion setup
- Provide a better pillkeeper alternative use--SBB

correct logic for doubling potions

---

package.json
src/embezzler.ts
src/fights.ts
yarn.lock

I feel like this needs testing more than it does reviews

libram update; counters fixes

---

src/diet.ts

Push the counters fixes strictly before this; 0.6.11 breaks current counter shenanigans

libram diet changes

---

src/index.ts
src/lib.ts

@libraryaddict :eyes:
Status: needs testing & review, would like Irrat's eyes specifically on this because she requested/suggested it

fight stephen spookyraven if relevant

---

src/fights.ts

Conditions being
1) Must own SBB charter
2) Mall price of UMD > how much we would obtain from the 2nd choice
3) At least 7 days have elapsed since the last UMD was obtained

Grab a UMD if conditions are right

---

src/index.ts

Set potentially relevant prefs before running simdiet

---

src/fights.ts

Also prioritize Chest X-Ray fight to X-Ray and otoscope concurrently

Use otoscope for sandworms

---

package.json
src/fights.ts
src/mood.ts
src/outfit.ts
src/yachtzee.ts
yarn.lock

Relies on [libram PR 311](https://github.com/Loathing-Associates-Scripting-Society/libram/pull/311) and [libram PR 308](https://github.com/Loathing-Associates-Scripting-Society/libram/pull/308)

update libram; get rid of june cleaver maximizer issue; restore more mp at once

---

src/yachtzee.ts

also, default throwOnFail for potion acquisition to false

Use mallPrice for necessary items that we are looking to buy

---

src/diet.ts
src/fights.ts

Now we have 3 more Liver Space, grabbing High-End Ginger Wine if we have the outfit might be sensible, and more profitable than cigarettes?

add getting High-End Ginger Wine as an option

---

package.json
src/diet.ts
src/dropsgear.ts
src/index.ts
yarn.lock

Reverts Loathing-Associates-Scripting-Society/garbage-collector#996

Revert "Libram-6-19"

---

src/wanderer.ts

wal-mart gift certificates from VYKEA
Beach bucks from Fun Guy mansion
coinspiracy from The Deep Dark Jungle
Not doing fun funds since we already spend time in barf
Unknown drop rate, using 5% for now based on some casual log searching

Wanderer lovebug currency value

---

src/dailies.ts

Reverts Loathing-Associates-Scripting-Society/garbage-collector#1006

Revert "Support using absentee voter ballot"

---

src/yachtzee.ts

This fix is bad for people who somehow use the edpiece meat% while another item (e.g. scuba) for underwater breathing, but no such cases have been reported thus far

Fix edpiece when it's both the best breathing source and meat% hat

---

src/fights.ts

astral pilsners should not be counted as a potential "best consumable" when considering whether to get ginger wine vs cigarettes

dont consider astral pilsners as "best consumable"

---

src/wanderer.ts

support castle top floor carto adventure

---

README.md

A bit confusing for new users, so best to remove this now that it no longer exists.

Remove FAQ question about IotM tracking preference

---

src/dailies.ts

don't yoink cars unless we have to

---

src/outfit.ts
src/yachtzee.ts

Automatically triggered if we cannot get sufficient turns of synth after a full length chain

Support shorter length chains

---

src/extrovermectin.ts
src/familiar/freeFightFamiliar.ts
src/familiar/itemFamiliar.ts
src/familiar/lib.ts
src/familiar/marginalFamiliars.ts
src/fights.ts
src/index.ts

@Pantocyclus this will make me able to fiddle with the jellyfish code in the barfTurn restructure more easily

Allow us to pass location and other options to freeFightFamiliar

---

src/yachtzee.ts
src/yachtzee/buffs.ts
src/yachtzee/diet.ts
src/yachtzee/familiar.ts
src/yachtzee/fishy.ts
src/yachtzee/index.ts
src/yachtzee/lib.ts
src/yachtzee/outfit.ts

Bell spikes yachtzee

---

src/wanderer.ts

adding choice handling for the chain-to NCs from haunted bedroom

adding choice advs for haunted bedroom

---

src/embezzler.ts

Should we throw something that isn't ignored if we don't see that "Check out the gift shop" text?

Unlock beach for toastergazing

---

src/combat.ts

Could also do something like
```
.externalIf(
myFamiliar() === $familiar`Space Jellyfish`,
Macro.externalIf(
get("_spaceJellyfishDrops") < 5,
Macro.if_(
$monsters`angry tourist, garbage tourist, horrible tourist family`,
Macro.trySkill($skill`Extract Jelly`)
),
Macro.trySkill($skill`Extract Jelly`)
)
)
```

Jellyfish against sausage goblins when relevant

---

src/combat.ts
src/extrovermectin.ts
src/mood.ts

Initial AWoL support - casts long Con on crates and garbage tourists at appropriate moments, and adds the meat walk to the meat mood

Use Long Con & Lesiurely Amble

---

src/fights.ts

We can use spit jurassic acid as a free kill against sandworms.
It should be available because its normal usage doesn't come until barf turns?

Spit acid sandworm

---

src/dropsgear.ts

Lower the value to be more in line with current market conditions

Update the value of Cheeng's spectacles

---

src/lib.ts

Don't need to check if you're a Sauceror, since you can't generate soulsauce otherwise.

Cast Soul Food if you have Soulsauce

---

src/diet.ts
src/fights.ts
src/index.ts
src/yachtzee/diet.ts
src/yachtzee/fishy.ts
src/yachtzee/index.ts
src/yachtzee/lib.ts

(1) Delay freeRunFights() to post-yachtzeechain to save on LTBs 
(2) Consider Pocket Wishes as a Fishy source 
(3) Support liver cleansers within the yachtzeechain diet

Various yachtzeechain optimisations

---

src/wanderer/lib.ts

just a lil one to make sure we skip icy peak when we're supposed to.

using skiplist

---

src/fights.ts

Sssshhsssblllrrggghsssssggggrrgglsssshhssslblgl

---

src/yachtzee/diet.ts
src/yachtzee/index.ts

Also support < level 13 chains

Support pure parka chains

---

package.json
src/index.ts
src/post.ts
yarn.lock

Drafting this prior to testing; 7.2 was a big one

New libram; first round of fallbot support

---

src/diet.ts

Fixing this bug was worth the 180k it cost me.

useIfUnused checks if the property is NOT true

---

src/post.ts

dont send out the fallbot if the turns for the next quest is more than your current turns left (+10) when not ascending

Dont send fallbot out before rollover

---

src/diet.ts

Maybe `_universalSeasoningUsed` is an old pref?

Properly use universal seasoning

---

src/dropsgear.ts

I said I would stop thinking about it but I could not.
I feel _fairly_ decent about this, but still somewhat unsure.
If it looks okay to others, I can test it once I'm done my stint in hardcore

June cleaver queue consideration

---

src/tasks/dailyItems.ts

you can smash extra hats and also this opens it up if we want to get the fat loot token with free kills

Open FantasyRealm and get the hat

---

src/dropsgear.ts

Chances left can't be less than 0

June cleaver oops

---

src/embezzler.ts
src/fights.ts
src/yachtzee/index.ts

Dont attept to fight witchess monsters by getting lucky and going to knob treasury. Witchess monsters dont have embezzler basemeat

Cant get lucky for Witchess, Fix witchess basemeat

---

src/yachtzee/diet.ts
src/yachtzee/index.ts

Also update sweat tracking using visitUrl to the sweatpants

Shrug phat loot before diet

---

src/index.ts

This would be useful for full-day wrapper scripts that have a nobarf task.

Track completion via preference

---

src/post.ts
src/wanderer/lib.ts

El Vibrato is very variable as a YR location, but more importantly each adventure there ticks down the counter to the zone closing.
It is a pretty good autumn-aton location.
You can also make 200k out of your polar pockets if you map (or reminisce etc.) a towering construct. Don't really understand how I'd change that part of the code, though.

feat: don't use El Vibrato as a wanderer location. Do autumnaton it.

---

package.json
src/combat.ts
src/index.ts
yarn.lock

This way we don't print out "CCS set to garbo" every adventure.

Use setCcs rather than prefs to set CCS.

---

src/config.ts
src/potions.ts

Discussion for this functionality roughly started here: https://discord.com/channels/466605739838930955/756649296774037567/1062567486731603998.

Enable usage of porcelain candy dishes

---

src/index.ts

Accept it as a starting garden, harvest it appropriately.

feat: support rock garden

---

src/config.ts
src/workshed/index.ts

Added substring matching and initials matching to config. 
Also supports switching out of DNA lab, as well as trainset -> CMC (and should in general switch to whatever workshed the user intended to after we run out of turns)

More workshed features

---

src/index.ts

At the end of each session, garbo says I've earned 900m meat from items. This isn't quite true.

feat: don't count sheet in valuation

---

package.json
src/barfTurn.ts
src/combat.ts
src/dropsgear.ts
src/familiar/lib.ts
src/index.ts
src/mood.ts
src/outfit.ts
src/wanderer/lib.ts
yarn.lock

Support for Pig Skinner red-ray, Cheese Wizard yellow ray and Stilton Splatter, and Jazz Agent buffs

Add initial support for Avatar of Shadows Over Loathing

---

src/post/workshed.ts

For now this just saves CMC until you have 105 estimated turns remaining, that way you get the most out of DNA lab or model train set.

Delay installing workshed until end if possible

---

src/tasks/ascending.ts
src/tasks/dailyItems.ts

Remove unnecessary brackets

---

src/fights.ts
src/potions.ts

Also improve free action checks

Don't add rufusPotion if we don't have the payphone

---

src/mood.ts
src/tasks/daily.ts

Garbo will currently spend an adventure to get "Do I Know You From Somewhere?" if you used all your free beach walks before running it

Check for free beachwalks available before getting effect

---

package.json
src/diet.ts
src/fights.ts
src/index.ts
src/tasks/dailyItems.ts
yarn.lock

This needs a new libram that is yet to be published

Support Shadow Forest

---

src/post/autumnaton.ts
src/tasks/daily.ts

avoid cleaver

---

src/dropsgear.ts
src/lib.ts
src/outfit.ts
src/potions.ts
src/yachtzee/buffs.ts

we generally shouldn't have effectful code in something like meatDrop, and this has the dangerous side effect of making it never think we're at barf mountain for things like sunglasses

Set-location-to-barf

---

src/diet.ts
src/index.ts

`retrieve_price()` has inconsistent behaviour with `mall_price()` and `npc_price()`.
Specifically, `retrieve_price()` returns infinity (or a very large number) when it deems the item unacquireable, while `mall_price()` and `npc_price()` return 0.

retrieve_price() fix

---

src/wanderer/lib.ts

The NC no longer shows up after defeating Ed, but mafia will still show the combat rate being 85.

Upper chamber has no NCs after finishing

---

src/wanderer/lib.ts

Reverts Loathing-Associates-Scripting-Society/garbage-collector#1368

Revert "update choice adventure sequence for spooky forest nc"

---

src/fights.ts

Idea: consider using `molehill mountain` since it's a free fight

Check buffed Muscle before using Powerful Glove and prefer Moleman for Thesis

---

package.json
yarn.lock

been a bit since we upgraded dependencies

run yarn upgrade

---

.vscode/settings.json

Prefer spaces for vscode

---

src/mood.ts
src/tasks/daily.ts

Requires https://github.com/loathers/libram/pull/478.

Switch beach comb tasks to BeachComb.available().

---

src/wanderer/lib.ts

Fix choices for wandering in the castle basement

---

package.json
src/fights.ts
src/index.ts
src/outfit/free.ts
src/tasks/dailyItems.ts
yarn.lock

Requires either yachtzeechain or !nobarf

Pledge allegiance

---

src/combat.ts
src/outfit/dropsgear.ts
src/post/index.ts
src/tasks/dailyFamiliars.ts

Took a crack at this.
I've swapped around how the Feliz Value is handled so that I can export and use it
This will require the user to have manuel so that we can safely use pinata while doing stasis before critting.

Cincho Projectile Pinata

---

src/combat.ts
src/outfit/dropsgear.ts
src/post/index.ts
src/tasks/dailyFamiliars.ts

This reverts commit ecd629ae37e778373a54153d8a2bd2f628bc729a.

Revert "Cincho Projectile Pinata (#1420)"

---

package.json
src/outfit/free.ts
yarn.lock

Reverts Loathing-Associates-Scripting-Society/garbage-collector#1466

Revert "Upgrade grimoire; use `addbonuses`"

---

src/fights.ts

More accurately value each point of item drop.
Also don't value item drop if it's above 10,000 (probably doesn't matter, but might as well)

Sandworm spec specific bonus

---

src/dailies.ts
src/dailiespost.ts
src/tasks/ascending.ts
src/tasks/daily.ts
src/tasks/dailyFamiliars.ts
src/tasks/dailyItems.ts
src/tasks/dailyVolcano.ts
src/tasks/engine.ts
src/tasks/postFreeFight.ts

Garbo daily tasks as quests

---

package.json
src/fights.ts
yarn.lock

Works the same as extinguisher, so we can just stick it in there, I think.

Perpetrate mild evil

---

src/outfit/embezzler.ts
src/outfit/free.ts

Add bonus value for guzzlr pants

---

src/tasks/daily.ts

one goddamn comment on voting booth

---

package.json
src/index.ts
src/yachtzee/diet.ts
yarn.lock

Also bump mafia version for aug skills to work properly

Yachtzee mojo fix

---

src/embezzler.ts

My prettier on save is removing the commas, I am unsure what's happening

Check treasury availability

---

package.json
src/combat.ts
src/embezzler.ts
src/extrovermectin.ts
src/index.ts
yarn.lock

- Move to daily monster habitat flags
- Update since for correct monster habitat props

Monster habitats now daily

---

src/clan.ts

this is why we can't have nice things

No more clan stash printouts

---

.github/workflows/build.yml

why are we not doing this already

Run yarn build in PRs

---

src/extrovermectin.ts

Prompt users if they would like to install an ice house to save on banishers. If they decline, they will not be notified again.

Use ice house

---

packages/garbo/src/tasks/barfTurn.ts

need to check pocket prof exp for thesis

---

packages/garbo/src/tasks/daily.ts

Add Clan Fortune Consults task

---

packages/garbo/src/tasks/barfTurn.ts
packages/garbo/src/tasks/engine.ts

handle voter inebriety

---

packages/garbo/src/fights.ts

temp fix until grimorized. probably fixes #1577

Don't freerun if no adventures

---

packages/garbo/src/embezzler/fights.ts

This probably breaks a bunch of stuff, but it stops the most immediate breakage

remove toastergazing

---

packages/garbo/src/tasks/dailyFamiliars.ts

We'll need to estimate the value eventually

Don't abort if box of Familiar Jacks is expensive

---

packages/garbo/src/embezzler/fights.ts

Reverts loathers/garbage-collector#1654

add toastergaze stub function for future generations

---

packages/garbo/src/tasks/freeFight.ts

Just some lost stuff in the migration to grimoire

Re-add ML reductions to glitch

---

packages/garbo/src/tasks/barfTurn.ts

I got stuck looping this NC, as choice three just leaves the adventure

fix DD trap choice

---

packages/garbo/src/tasks/barfTurn.ts

```
Took choice 692/3: pick lock with lockpicks, no turn spent
```

use lockpicks

---

packages/garbo/src/tasks/barfTurn.ts

for Interview With You (a Vampire). already tested

Vamp out if profitable

---

packages/garbo/src/dailies.ts
packages/garbo/src/tasks/dailySea.ts
packages/garbo/src/tasks/index.ts

Unlock the sea and get sea jelly daily with space jellyfish

Acquire sea jelly

---

packages/garbo/src/outfit/dropsgear.ts

Support Sneegleeb and can of mixed everything

---

packages/garbo/src/fights.ts

Having an Obtuse Angel but not a quake of arrows would lead to an abort of "unable to satisfy famspec". Try to work around that.
It costs ~50k in the mall and can rise substantially, so it can breach your auto-buy price limit.

fix: don't assume we can get a quake of arrows

---

packages/garbo/src/acquire.ts
packages/garbo/src/diet.ts
packages/garbo/src/tasks/daily.ts

This will have to wait for whet stone in libram here:
[https://github.com/loathers/libram/pull/538](https://github.com/loathers/libram/pull/538)

Diet and Dailies

---

packages/garbo/src/tasks/post/index.ts

can only cleave when we have turns

---

packages/garbo-lib/src/wanderer/index.ts
packages/garbo-lib/src/wanderer/lib.ts

handle carto NC for frat house

---

packages/garbo/src/tasks/post/index.ts

Friar loop fix

---

packages/garbo/src/tasks/post/worksheds.ts

Resolves this: https://github.com/loathers/garbage-collector/issues/1702#issuecomment-1790067912

only attempt workshed tasks for worksheds with an action

---

packages/garbo/src/fights.ts

I've found my extinguisher isn't getting used, because I burn all my non-familiar free runs on the jellyfish, and because it requests that I use the xo skeleton.
Long-term, we should streamline this logic when we grimoirize, make it less terrible. Short-term, I feel like this is good. Gingerbread as a wanderer target means that it's less important to get in there with free runs, and imo this is more valuable than marginal jellyfish-turns (less valuable than your first jellyfish turn, but we do take care of that during barf at EOD)

move extinguisher above jellyfish & gingerbread

---

packages/garbo-lib/src/wanderer/lib.ts

spacegate to skiplist

---

packages/garbo/src/tasks/barfTurn.ts

Resolves #1740; I think having the fight be two separate tasks instead of one with hella diverging behavior is better

fix handling of underwater embezzler during barf-turn

---

packages/garbo/src/tasks/dailyItems.ts

Do we want to reserve any leaves or just do this every day? Or maybe move to barfTurn so it will buy them when leaves are acquired?

Burn leaves for 3x lit leaf lasso & day shortener

---

packages/garbo/src/resources/latte.ts
packages/garbo/src/tasks/barfTurn.ts

Use set equal

---

packages/garbo-lib/package.json
packages/garbo-lib/src/wanderer/lib.ts

no more wandering in the monorail

---

packages/garbo/src/tasks/freeFight.ts

should maybe rename "freefight" to "freekill"; resolves #1789

kramco is a "wanderer" type, not a "freefight" type

---

packages/garbo/src/outfit/barf.ts

With costs increasing for ice nine, probably better to just the 5 fam weight with love instead of paying ~70k for ice nine.

use love as a gun if we have it

---

packages/garbo-lib/src/wanderer/lib.ts

Superlikely unskippable "Highway to Hey Deze" non combat

Don't wander at Pandamonium Slums

---

packages/garbo/src/tasks/dailyItems.ts

Because this is an actual snarfblat it needs some extra edge case handling.
We don't want to go there overdrunk unless we have wineglass, and I added extra tries to the skip limit in case we hit things like June Cleaver there (might have it equipped in offhand when not drunk?)

Candy cane sword cane failsafes

---

packages/garbo/src/embezzler/fights.ts

Flip equality when we're targeting embezzlers specifically

Flip equality on embezzler clover check

---

packages/garbo-lib/src/wanderer/index.ts
packages/garbo/src/index.ts
packages/garbo/src/tasks/post/index.ts

Universal Recovery messes up June Cleaver stuff

Blank out recovery script while running garbo

---

packages/garbo/src/familiar/barfFamiliar.ts
packages/garbo/src/outfit/barf.ts
packages/garbo/src/session.ts
packages/garbo/src/tasks/barfTurn.ts

Reverts loathers/garbage-collector#1651

Revert "MPA Session Calculation"

---

packages/garbo/src/resources/realm.ts
packages/garbo/src/tasks/barfTurn.ts

pick up and exchange the fused fuse at EOD

---

packages/garbo/src/tasks/dailyItems.ts
packages/garbo/src/tasks/post/index.ts

Upon seeing that it was in dailyItems, I'm not actually sure how desirable this is.

use the wardrobe-o-matic at level 20

---

packages/garbo-lib/package.json
packages/garbo-lib/src/wanderer/index.ts
packages/garbo-lib/src/wanderer/lib.ts
packages/garbo/src/embezzler/staging.ts
packages/garbo/src/fights.ts
packages/garbo/src/garboWanderer.ts
packages/garbo/src/yachtzee/lib.ts

- **Delay unsupportedchoices in garbo-lib and add Ice Hotel choice**
- **Delay quartet choice too**
- **Bump for breaking changes to garbo-lib**

Support delayed support choices

---

packages/garbo/src/tasks/dailyItems.ts

filter experienceFamiliars by a lower experience threshold for piccolo

---

packages/garbo/static/dependencies.txt

Move to loathers combo from LASS

Update Combo Dependency

---

packages/garbo/src/index.ts
packages/garbo/src/tasks/barfTurn.ts

- **Grab Law of Averages adventures when possible.**
We can get a few more adventures per day from this. ~Draft until https://github.com/kolmafia/kolmafia/pull/2298 is merged and I can use the correct revision for our since declaration.~

Law of Averages Support

---

packages/garbo/src/lib.ts

I forgot to account for it costing an adventure

Fix overvaluing inhaler lucky

---

packages/garbo/src/familiar/constantValueFamiliars.ts
packages/garbo/src/familiar/freeFightFamiliar.ts

Currently we're valuing constant value familiars during free fights that only get value during barf

constantValueFamiliars mode

---

packages/garbo/src/tasks/daily.ts

Occasionally visiting this latte store page will break the preference, check for it being malformed

Latte Preference Safeguard

---

packages/garbo/src/lib.ts

Some time after visiting the Violet Fog, under unknown, mysterious circumstances you might get a "flashback" where you visit the Violet Fog again. These encounters are weird, and might lead to spent turns etc.
Added an option for including them because the others had one but realistically I think it's always going to want to be true.

feat: violet fog flashbacks are weird

---

packages/garbo/src/fights.ts
packages/garbo/src/lib.ts
packages/garbo/src/resources/extrovermectin.ts
packages/garbo/src/yachtzee/lib.ts

This replaces the previous check that was just for latte, and allows to pass in an OutfitSpec to check against

Check for equipment conflicts in freeRunConstraints

---

packages/garbo/src/tasks/barfTurn.ts

Avoid high ML items in Caldera

---

packages/garbo/src/clan.ts
packages/garbo/src/index.ts

check your terrarium for familiar equipment when returning to the stash

---

packages/garbo/src/index.ts

Reverts loathers/garbage-collector#1884

Revert "Buff and extend before freefights"

---

packages/garbo/src/fights.ts
packages/garbo/src/tasks/freeFight.ts

untested as I cannot access the red zeppelin but i think this is correct

grimoire task for glark cable

---

packages/garbo/src/combat.ts
packages/garbo/src/outfit/barf.ts
packages/garbo/src/outfit/dropsgearAccessories.ts

idk if this would help anyone???

Kodiak Moment is a crit source with both bear arms

---

packages/garbo/src/lib.ts

use `lastMonster` for Sssshhsssblllrrggghsssssggggrrgglsssshhssslblgl

---

packages/garbo/src/tasks/barfTurn.ts

don't pass `undefined` into `freeFightOutfit` while pretending to not have a key

---

packages/garbo/src/embezzler/fights.ts
packages/garbo/src/lib.ts
packages/garbo/src/resources/scepter.ts

only embezzlers can be found lucky at the treasury, as it turns out

---

packages/garbo/src/outfit/embezzler.ts

don't use ELP underwater

---

packages/garbo/src/combat.ts

Use delevelers and stuns on mimes

Delevel mimes

---

packages/garbo/src/combat.ts

reorder kill skills if swole

---

packages/garbo/src/lib.ts
packages/garbo/src/outfit/dropsgear.ts
packages/garbo/src/outfit/dropsgearAccessories.ts

if seal clubber or pig skinner

simple crits for copy target

---

packages/garbo/src/lib.ts

handle empty json string more gracefully

---

packages/garbo/src/fights.ts

it should be fine i pulled the free fight familiar out of the !underwater check right?

probably fix duping for me

---

packages/garbo/src/target/fights.ts
packages/garbo/src/tasks/freeFight.ts

Defer witchess if it is our copy target

---

packages/garbo/src/tasks/freeFight.ts

remove robort until i understand how to do this

---

packages/garbo/src/familiar/barfFamiliar.ts
packages/garbo/src/familiar/constantValueFamiliars.ts
packages/garbo/src/familiar/dropFamiliars.ts
packages/garbo/src/familiar/index.ts
packages/garbo/src/familiar/lib.ts
packages/garbo/src/fights.ts

account for soups

---

packages/garbo/src/target/fights.ts

use the mimic egg from clinic correctly

---

packages/garbo/src/tasks/freeGiantSandworm.ts

use garboValue for sandworms

---

packages/garbo/src/combat.ts

This should allow us to handle #2121 more easily

slightly restructure GarboStrategy to allow customizing behavior with unexpected guests

---

packages/garbo/src/tasks/freeGiantSandworm.ts

This has some weird order-of-operations issues with champagne bottle, and fails to solve the issue of the quad-tom

Sandworm-valuation-changes

---

packages/garbo/src/tasks/freeFight.ts

fix ready/completed check for portscan macro mushroom

---

packages/garbo/src/tasks/barfTurn.ts

only check `itemAmount` not `availableAmount`

---

packages/garbo/src/resources/gingerbread.ts

only do midnight in gingerbread locations to which we have access

---

packages/garbo/src/target/fights.ts

potential needs to account for available for witchess as a target fight

---

packages/garbo/src/index.ts
packages/garbo/src/tasks/daily.ts

Resolves #2203 (previously closed due to lack of session log)

dispose of park garbage even when nobarfing

---

packages/garbo/src/index.ts

moving help above mallprices & main.php check

---

packages/garbo/src/combat.ts

resolves #2232, probably
and even #1520 I think

redigitize smarter?

---

packages/garbo/src/tasks/freeFight.ts

also add bonuses for eldritch equipment

Simplify sssshhsssblllrrggghsssssggggrrgglsssshhssslblgl macro

---

packages/garbo/src/familiar/constantValueFamiliars.ts
packages/garbo/src/familiar/dropFamiliars.ts
packages/garbo/src/familiar/experienceFamiliars.ts
packages/garbo/src/familiar/freeFightFamiliar.ts
packages/garbo/src/familiar/index.ts
packages/garbo/src/familiar/lib.ts
packages/garbo/src/fights.ts
packages/garbo/src/outfit/free.ts
packages/garbo/src/outfit/index.ts
packages/garbo/src/tasks/barfTurn.ts
packages/garbo/src/tasks/freeFight.ts

We should test this for a couple of days before merging but also I think this is phase 0 of TCB support

add tracking for which familiars work on free run

---

packages/garbo-lib/src/value.ts

Resolves #2252 better than the hotfix did

just make unit cost infinite for unbuyable items

---

packages/garbo-lib/src/wanderer/lib.ts

can't YR in your mushroom garden

---

packages/garbo/src/fights.ts

Prevent mafia abort, stats are nominal who cares. Resolves #1873

Don't equip makeshift garbage shirt in some cases

---

packages/garbo-lib/src/wanderer/index.ts
packages/garbo/src/fights.ts
packages/garbo/src/tasks/barfTurn.ts
packages/garbo/src/tasks/freeFight.ts

better ghost NC handling

---

packages/garbo/src/tasks/dailyItems.ts

always check that deviled egg candies are candies

---

packages/garbo/src/acquire.ts
packages/garbo/src/tasks/freeFight.ts

Add price caps for self-dribbling basketballs

---

packages/garbo/src/familiar/toyCupidBowFamiliar.ts

respect settings for `choiceAdventure768` for the mini adventurer

---

packages/garbo/src/familiar/toyCupidBowFamiliar.ts

no hipster or goth for TCB

---

packages/garbo/src/outfit/free.ts

pass the value not the map itself

---

packages/garbo/src/familiar/lib.ts

clamp tcb turns properly

---

packages/garbo/src/index.ts

clear the equipment of familiars that are plausibly hogging stuff we need

---

packages/garbo/src/diet.ts

shrug songs to cast ode

---

packages/garbo/src/tasks/freeGiantSandworm.ts

acquire shadow brick

---

packages/garbo-lib/src/wanderer/lib.ts

don't adventure at mt. molehill

---

packages/garbo-lib/src/wanderer/lib.ts

I don't know that this'll be our long-term answer to this, but it is our short-term answer to this.

ban wandering in agua zones

---

packages/garbo/src/resources/chestMimic.ts
packages/garbo/src/target/fights.ts

only try to do barf eggs if we can

---

packages/garbo/src/tasks/barfTurn.ts

only get lucky if you aren't lucky; always use your lucky when you can

---

packages/garbo-lib/src/wanderer/index.ts
packages/garbo-lib/src/wanderer/lib.ts

Resolves #2459
long-term, it'd be good to make this vary by the moonlight (although they can only be done when truly guaranteed)

ban certain monsters from being peridoted

---

packages/garbo/src/tasks/freeFight.ts

We were running things like Protonic ghosts while we had teleportitis effect

Don't run free fights while we have feeling lost for sandworms

---

packages/garbo/src/familiar/dropFamiliars.ts

fix for green pixie absinthe minded

---

packages/garbo-choice/src/resources/mobius.ts
packages/garbo/src/outfit/target.ts
packages/garbo/src/tasks/barfTurn.ts
packages/garbo/src/tasks/engine.ts

I changed my mind this will fix it enough that I can write
resolves #2499

just the best anapests

---

packages/garbo/src/acquire.ts

Increase aggregate cost safety
